on:
  pull_request:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}

      AWS_REGION: us-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          TAG: ${{ env.TAG }}
        run: |          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: |
            TAG=${{ env.TAG }}
            AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_REGION=us-east-1
            AWS_REGISTRY_URL=${{secrets.AWS_REGISTRY_URL}}
            REPOSITORY_NAME=${{secrets.REPO_NAME}}
            EXPOSED_PORT=${{secrets.EXPOSED_PORT}}
            APPLICATION_PORT=${{secrets.APPLICATION_PORT}}
          script: |                      
            
            echo "AWS credentials set...."
            export AWS_ACCESS_KEY_ID=${ARGS}
            export AWS_SECRET_ACCESS_KEY=${TARGET}
            export AWS_REGION=${AWS_REGION}            
            export EXPOSED_PORT=${EXPOSED_PORT}
            export APPLICATION_PORT=${APPLICATION_PORT}
            
            echo "AWS CLI version: $(aws --version)"
            echo "Docker version: $(sudo docker --version)"
            
            echo "Stop the current running container if exist..."
            sudo docker stop wd-dm-app || true
    
            echo "Remove the previous container..."
            sudo docker rm wd-dm-app || true
            
            echo "Logging in to ECR...."
            sudo aws configure                                                                                   
            sudo aws ecr get-login-password --region us-west-1 | sudo docker login --username AWS --password-stdin 445567104363.dkr.ecr.us-west-1.amazonaws.com          
            
            echo "AWS_REGISTRY_URL: ${{ env.AWS_REGISTRY_URL }}"
            echo "REPOSITORY_NAME: ${{ env.REPO_NAME }}"
            echo "TAG: ${{ env.TAG }}"
            
            echo "Pulling  image from ECR..."
            sudo docker pull ${{ env.AWS_REGISTRY_URL }}/${{ env.REPO_NAME }}:${{ env.TAG }}
            
            echo "Running the container..."
            sudo docker run -d \
              --name wd-dm-app \
              --env-file  /path/to/dot/env \
              -p ${{ env.EXPOSED_PORT }}:${{ env.APPLICATION_PORT }} "${{ env.AWS_REGISTRY_URL }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}"
            
            
        
            
            
