on:
  pull_request:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
      PRIVATE_SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: |
            TAG=${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
            AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_REGION=us-east-1
          script: |                      
            
            echo "AWS credentials set...."
            export AWS_ACCESS_KEY_ID=${ARGS}
            export AWS_SECRET_ACCESS_KEY=${TARGET}
            export AWS_REGION=${AWS_REGION}
            
            echo "AWS CLI version: $(aws --version)"
            echo "Docker version: $(sudo docker --version)"
            
            echo "Stop the current running container if exist..."
            sudo docker stop container_name || true
    
            echo "Remove the previous container..."
            sudo docker rm container_name || true
            
            echo "Logging in to ECR...."
            sudo aws configure                                                                                   
            sudo aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 445567104363.dkr.ecr.us-east-1.amazonaws.com/wd-app
            echo "Logged in successful..."
            
            echo "Pulling  image from ECR..."
            echo "Docker pull command: sudo docker pull \"${{ secrets.AWS_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:${{ env.TAG }}\""
            echo "Docker pull completed..."
        
            
            
